FROM node:22.11-alpine AS gb3-dev

# Provide overrides for APP_VERSION and APP_RELEASE as build-args and expose them as ENV variables for the update-version.js script
ARG APP_VERSION
ARG APP_RELEASE
ENV APP_VERSION=$APP_VERSION
ENV APP_RELEASE=$APP_RELEASE
ENV NODE_ENV=development
ARG TARGET_ENVIRONMENT=local-gb2

# Zeitzone & Zertifikate
RUN ln -s /usr/share/zoneinfo/Europe/Zurich /etc/localtime && \
    mkdir -p /usr/local/share/ca-certificates/

COPY  ./dev/certificates/zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt

RUN apk --no-cache add --no-check-certificate ca-certificates git && \
    update-ca-certificates

WORKDIR /app

# Copy the certificate to a temporary location and configure npm to use it
RUN npm config set cafile /usr/local/share/ca-certificates/zscaler-root-ca.crt

# Install project dependencies
COPY ./package*.json ./
RUN npm ci --ignore-scripts

# Copy the rest of the application code
COPY . .

# Expose the port the Angular development server runs on
EXPOSE 4242

# Start the Angular development server
CMD ["npm", "run", "start-local-gb2"]

