#!/usr/bin/env bash
LC_ALL=C

echo "🚀 Running linter!"
npx pretty-quick --staged
echo ""

echo "🚀 Checking branchname!"
local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex='^((hotfix|feature)\/gb3-[0-9]*-[a-zA-Z0-9\-]+)$'

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo -e "\033[31m⚠️ Branchname does not adhere to naming convention $valid_branch_regex! \e[0m"
else
  echo -e "✅  Branchname!"
fi
echo ""
